apiVersion: v1
kind: Service
metadata:
  name: hyc-proxy
  labels:
    app.kubernetes.io/name: hyc-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hyc-proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyc-proxy
  labels:
    app.kubernetes.io/name: hyc-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hyc-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hyc-proxy
    spec:
      containers:
      - image: pprecel/hyc-proxy:hyc2021
        imagePullPolicy: Always
        name: hyc-proxy
        ports:
        - containerPort: 8080
          name: http
